--- # Bootstrap Webservers

- name: Install apache  
  yum:
    name: httpd
    state: latest

- name: install firewalld
  action: yum name=firewalld state=installed
  
- name: Enable firewalld on system reboot
  service: name=firewalld enabled=yes

- name: Enable Apache on system reboot
  service: name=httpd enabled=yes

- name: Open port 80 for http access
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Restart service firewalld
  service:
    name: firewalld
    state: restarted      

- name: Create web-root directory
  file:
    path: /var/www/{{ domain }}
    state: directory
    owner: "{{ ansible_ssh_user }}"
    mode: '0755'

- name: create index.html file
  file:
    name: /var/www/html/index.html
    state: touch

- name: add web content
  lineinfile:
    line: " {{ domain_name }} is is a test"
    path: /var/www/html/index.html

- name: Restart httpd
  service:
    name: httpd
    state: restarted

- name: Restart the firewalld service to load in the firewall changes
  service: 
    name: firewalld 
    state: restarted

- name: Restart httpd
  service:
    name: httpd
    state: restarted