---
# tasks file for ec2_key

- name: Create a new EC2 keypair
  ec2_key:
    name: "{{ keypair }}"
    region: "{{ region }}"
  register: ec2_key_result

- name: Save private key
  copy: content="{{ ec2_key_result.key.private_key }}" dest="~/.ssh/{{ keypair }}.pem" mode=0600
  when: ec2_key_result.changed
